games:
- name: Cheat Engine.exe
  alias: Cheat Engine
  isEnabled: true
  hDREnabled: true
- name: Project_Plague.exe
  alias: 明末：渊虚之羽
  isEnabled: true
  hDREnabled: false
- name: Tales of Arise.exe
  alias: 破晓传说
  isEnabled: true
  hDREnabled: false
autoStartInteractiveMonitor: false
launchOnSystemStartup: false
