games:
  - entryId: string
    dataKey: string!
    executablePath: string
    executableName: string
    displayName: string
    isEnabled: bool
    hDREnabled: bool
    name: string
    alias: string
